version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: booking
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d

  api:
    image: node:22
    ports:
      - '3000:3000'
    volumes:
      - ./api:/usr/src/app
      - ./tests:/usr/src/app/tests
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run start"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/booking
    depends_on:
      - db
